[Data]

# # ---- volume ----
dataset_name = emissionlarge
num_of_vertices = 117
adj_filename = D:\gitroot\DT-DIMA-EM\data/flatbushlarge_5min_events40/flatbushlarge_adj_matrix.csv
# graph_signal_matrix_filename = data/flatbushlarge_5min_events40/flatbushlarge_volspd_attributes_5min_40events.npz

# the raw data is aggregated into every 5 minutes
points_per_hour = 12
num_for_predict = 12
len_input = 12

[Training]

use_nni = 1
batch_size = 24
model_name = CoordinatedCam
num_of_weeks = 0
num_of_days = 0
num_of_hours = 1
start_epoch = 0
epochs = 50
fine_tune_epochs = 50
learning_rate = 0.001
direction = 1
encoder_input_size = 2
decoder_input_size = 2
dropout = 0.0
kernel_size = 3
num_layers = 4
d_model = 64
nb_head = 8

smooth_layer_num = 0
alpha = 0.5
in_channels = 2

# spatial self attention
ScaledSAt = 1
# spatial encoding indicator
SE = 1     
# temporal encoding indicator
TE = 1     
# temporal context awareness indicator
aware_temporal_context = 1    

# below is GPU
multiGPU = 0
whichGPUs = 0,1
cudaID = 0

[Connector]
# volume_matrix_filename = data/emision_start/volume_matrix_pure_94.csv
# speed_matrix_filename = data/emision_start/speed_matrix_pure_94.csv
volume_matrix_filename = D:\gitroot\DT-DIMA-EM\data/emision_start/Event_Only/volume_matrix_pure_94.csv
speed_matrix_filename = D:\gitroot\DT-DIMA-EM\data/emision_start/Event_Only/speed_matrix_pure_94.csv
graph_edge_filename = D:\gitroot\DT-DIMA-EM\data/flatbush_volumespeed5min/flatbush_edge_look_up_table.csv
best_epoch = 98
sample_frame = 5
#params_path = experiments/flatbush/MAE_CoordinatedCam_h1d0w0_layer4_head8_dm64_channel1_dir1_drop0.00_1.00e-03TcontextScaledSAtSE0TE/epoch_92.params

[Controller]
num_agents = 37
num_features = 94
params_path = emision_carID/emission_ped_test1/
# data_dict = ./data/emision_start/volume_matrix_pure_94.csv
# data_dict2 = ./data/emision_start/speed_matrix_pure_94.csv
data_dict = ./data/emision_start/Event_Only/volume_matrix_pure_94.csv
data_dict2 = ./data/emision_start/Event_Only/speed_matrix_pure_94.csv
pedestrian_dict = ./data/emision_start/ped_vol_expanded.csv
em_dict = ./data/emision_start/Event_Only/edge_emission_94.xml
em_lst_path = ./data/emision_start/edge_emission_output_67.csv
# car_type_dict = ./data/emision_start/distribution_true/car_percentage/
car_type_dict = ./data/emision_start/Event_Only/count_matrix_pure_94_
# lane_dict = ./data/Final_Exp_newapr28/WZ_2_2/edge_event_matrix_acc0.csv
# lane_info_dict = ./data/Final_Exp_newapr28/WZ_2_2/events_lane_matrix_acc2.csv
# num_actions = 4
delta = 1
bar = 3
seed = 78
env_name = CustomEnvCam-v0
sample_frame = 5
connector_use = true
test_predictor = false
initial_time = 1440
rollout_length = 12
uniform = false
epsilon = 0.3
network_id = 2
beta = 0.7
ped_beta = 0.7
gamma = 1
ita = 0
rho = 10
# control acc!!!!!!
acc_num = 1

[Simulator]
simProjDir = ./sumo/exp/emission_ped_test1/
simMainFile = flatbush_game_large.sumocfg
randomSeed = 78
call_period = 30
